import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const switzer = localFont({
  src: [
    {
      path: './fonts/Switzer-Variable.woff',
      style: 'normal',
    },
    {
      path: './fonts/Switzer-VariableItalic.woff',
      style: 'italic',
    },
  ],
  variable: '--font-switzer',
});

export const metadata: Metadata = {
  title: 'Josefin Holgersson',
  description: 'Generated by create next app',
};

// Rot-layouten håller bara html/body och typsnitt. Navigation, main och footer
// ligger i (site)-gruppen så att (playground) kan rendera helt utan ramar.
const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={switzer.variable}>{children}</body>
    </html>
  );
};

export default RootLayout;
