import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Navigation from '@/components/Navigation';
import Footer from '@/components/Footer';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

const switzer = localFont({
  src: [
    {
      path: './fonts/Switzer-Variable.woff',
      style: 'normal',
    },
    {
      path: './fonts/Switzer-VariableItalic.woff',
      style: 'italic',
    },
  ],
  variable: '--font-switzer',
});

export const metadata: Metadata = {
  title: 'Josefin Holgersson',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={switzer.variable}>
        <Navigation />
        <main className="px-4 md:px-10 mb-32">{children}</main>
        <Footer />
      </body>
    </html>
  );
};
export default RootLayout;
